# Generated by Django 4.2 on 2024-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место выполнения')),
                ('time', models.TimeField(blank=True, default='12:00:00', null=True, verbose_name='Время начала выполнения')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная=1)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность выполнения, в секундах')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
